"""업비트·바이낸스 공용 UI, 거래소별 localStorage를 쓰는 매매 추적기."""
from __future__ import annotations

from pathlib import Path


JS = r'''(()=>{
const IS_BINANCE=location.pathname.includes('/binance/');
const EXCHANGE=IS_BINANCE?'BINANCE':'UPBIT';
const PIN_KEY=IS_BINANCE?'binancePins':'upbitPins';
const TRACK_KEY=IS_BINANCE?'okoTradeTrackerBinanceV1':'okoTradeTrackerUpbitV1';
const DATA=window.OKO_TRACK_DATA||{candidates:[],snapshot_at:''};
const COLORS={oldAvg:'#58bfff',oldStop:'#ff667e',oldT1:'#00e783',oldT2:'#00c7ff',nowAvg:'#ffd166',nowStop:'#ff9bac',nowT1:'#8ff0bd',nowT2:'#70c2ff'};
let chartInstances=[];
const parse=(s,d)=>{try{return JSON.parse(s)||d}catch(e){return d}};
const pins=()=>parse(localStorage.getItem(PIN_KEY)||'[]',[]);
const savePins=v=>localStorage.setItem(PIN_KEY,JSON.stringify(v));
const store=()=>parse(localStorage.getItem(TRACK_KEY)||'{}',{});
const saveStore=v=>localStorage.setItem(TRACK_KEY,JSON.stringify(v));
const num=v=>typeof v==='number'&&Number.isFinite(v)?v:(v!==null&&v!==''&&Number.isFinite(Number(v))?Number(v):null);
const price=v=>num(v)==null?'-':Number(v).toLocaleString('ko-KR',{maximumFractionDigits:8});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rowsFor=m=>(DATA.candidates||[]).filter(x=>String(x.market)===String(m)).sort((a,b)=>(num(b.score)||0)-(num(a.score)||0));
const current=(market,type)=>rowsFor(market).find(x=>x.type===type)||rowsFor(market)[0]||null;
function plan(r){
  const p=r?.trade_plan||{},entry=(r?.entry||[]).map(num).filter(x=>x!=null),targets=(r?.targets||[]).map(num).filter(x=>x!=null);
  const average=num(p.average_entry)??(entry.length?entry.reduce((a,b)=>a+b,0)/entry.length:null);
  return {current:num(p.current)??num(r?.price),entryLow:num(p.entry_low)??(entry.length?Math.min(...entry):null),entryHigh:num(p.entry_high)??(entry.length?Math.max(...entry):null),average,stop:num(p.stop)??num(r?.stop),t1:num(p.target1)??targets[0]??null,t2:num(p.target2)??targets[1]??null,status:p.status||r?.action||'확인 대기',remain:p.remain||(r?.missing||[]).join(' · ')||'현재 구조 확인',reason:p.reason||r?.reason||'-'};
}
function snapshot(r){const p=plan(r);return{exchange:EXCHANGE,market:r.market,name:r.name||r.market,type:r.type||'-',score:num(r.score),savedAt:new Date().toISOString(),analysisAt:DATA.snapshot_at||'',plan:p,charts:{day:(r.charts?.day||[]).slice(-180),h4:(r.charts?.['4h']||[]).slice(-180)}};}
function newRecord(r,reason='별표 등록'){const t=store(),id=`${r.market}|${r.type}|${Date.now()}`;t[id]={id,market:r.market,type:r.type,snapshot:snapshot(r),tracked:true,bought:false,events:[{at:new Date().toISOString(),text:`⭐ ${reason} · ${r.type}형 · ${price(plan(r).current)}`}],lastSig:''};saveStore(t);return id;}
function matchingRecord(t,market,type){return Object.values(t).find(x=>x.market===market&&x.type===type&&(x.tracked||x.bought));}
function ensurePinnedStructures(){const t=store();let dirty=false;for(const market of pins()){const rs=rowsFor(market),r=rs[0];if(!r)continue;const active=Object.values(t).filter(x=>x.market===market&&(x.tracked||x.bought));const oldStillExists=active.some(x=>rs.some(y=>String(y.type)===String(x.type)));const same=matchingRecord(t,market,r.type);if(!same&&!oldStillExists){const id=`${market}|${r.type}|${Date.now()}`;t[id]={id,market,type:r.type,snapshot:snapshot(r),tracked:true,bought:false,events:[{at:new Date().toISOString(),text:active.length?`🔵 새 구조 분리 저장 · ${r.type}형`:`⭐ 기존 별표를 고정 스냅샷으로 저장 · ${r.type}형`}],lastSig:''};dirty=true;}}if(dirty)saveStore(t);}
function verdict(item){const exact=(DATA.candidates||[]).find(x=>x.market===item.market&&x.type===item.type),any=rowsFor(item.market)[0],old=item.snapshot.plan||{};if(!exact&&any)return['🔵','새 구조 형성','blue',any];if(!any)return['🟡','계획 약화 · 대응 필요','yellow',null];const now=plan(exact);if(now.status==='구조 무효'||(num(old.stop)!=null&&num(now.current)!=null&&now.current<old.stop))return['🔴','당시 구조 무효','red',exact];const weak=['추격 금지','재탈환 확인','확인 대기','시장 대기','계획값 확인'];if(weak.some(x=>String(now.status).includes(x))||(num(exact.score)||0)<(num(item.snapshot.score)||0)-2)return['🟡','계획 약화 · 대응 필요','yellow',exact];return['🟢','당시 계획 유지','green',exact];}
function recordChanges(){const t=store();let dirty=false;for(const item of Object.values(t)){if(!item.tracked&&!item.bought)continue;const [icon,label,,r]=verdict(item),p=r?plan(r):null,sig=`${DATA.snapshot_at}|${icon}|${r?.type||'OUT'}|${r?.score??'-'}|${p?.status||'-'}|${p?.current??'-'}`;if(item.lastSig===sig)continue;item.lastSig=sig;item.events=item.events||[];item.events.push({at:new Date().toISOString(),text:`${icon} ${label}${r?` · 현재 ${r.type}형 · ${r.score??'-'}점 · ${price(p.current)}`:' · 현재 후보 이탈'}`});item.events=item.events.slice(-40);dirty=true;}if(dirty)saveStore(t);}
function compareBlock(title,r,p,date){return `<section><h4>${title}<small>${esc(String(date||'').replace('T',' ').slice(0,16))}</small></h4>${r?`<p><b>${esc(r.type)}형 · ${r.score??'-'}점</b></p><p>가격 ${price(p.current)}</p><p>진입 ${price(p.entryLow)} ~ ${price(p.entryHigh)} · 평균 ${price(p.average)}</p><p>구조 손절 ${price(p.stop)}</p><p>TP1 ${price(p.t1)} · TP2 ${price(p.t2)}</p><p class="track-state">${esc(p.status)}</p><p class="track-reason"><b>남은 조건</b> ${esc(p.remain)}<br><b>판단 근거</b> ${esc(p.reason)}</p>`:'<p><b>현재 스캔 후보에서 이탈</b></p><p class="track-reason">당시 계획은 그대로 보존돼. 다시 포착되면 현재 분석과 자동 비교해.</p>'}</section>`;}
function card(id,item){const [icon,label,cls,r]=verdict(item),old=item.snapshot.plan||{},now=r?plan(r):null,events=(item.events||[]).slice().reverse().map(e=>`<li><span>${esc(String(e.at||'').replace('T',' ').slice(0,16))}</span>${esc(e.text)}</li>`).join('')||'<li>아직 변화 기록 없음</li>';return `<article class="trade-track-card ${cls}" data-track-id="${esc(id)}"><div class="track-head"><div><b>${esc(item.snapshot.name||item.market)}</b><span>${esc(item.market)} · ${esc(EXCHANGE)} · 당시 ${esc(item.type)}형</span></div><div class="track-actions"><button class="buy-btn ${item.bought?'on':''}" data-buy="${esc(id)}">${item.bought?'💰 실제 매수함':'💰 실제 매수함'}</button><button data-untrack="${esc(id)}">별표 해제</button></div></div><div class="track-verdict"><strong>${icon} ${label}</strong><span>${item.bought?'실제 보유 표시 중':'관심 추적 중'}</span></div><div class="track-charts"><section><div class="track-chart-title"><b>일봉</b><span>당시선 + 현재선</span></div><div class="track-chart" data-chart="day"></div></section><section><div class="track-chart-title"><b>4시간봉</b><span>당시선 + 현재선</span></div><div class="track-chart" data-chart="4h"></div></section></div><div class="track-compare">${compareBlock('당시 계획',item.snapshot,old,item.snapshot.analysisAt||item.snapshot.savedAt)}${compareBlock('현재 분석',r,now,DATA.snapshot_at)}</div><details class="track-timeline"><summary>변화 기록 · ${(item.events||[]).length}건</summary><ul>${events}</ul></details></article>`;}
function host(){let h=document.getElementById('okoTradeTracker');if(h)return h;h=document.createElement('section');h.id='okoTradeTracker';h.className='oko-tracker';const root=document.getElementById('watchRoot');if(root){document.body.classList.add('tracker-watch-page');root.parentNode.insertBefore(h,root);}else{const intro=[...document.querySelectorAll('.page-intro')].pop();(intro||document.querySelector('main')||document.body).insertAdjacentElement('afterend',h);}return h;}
function line(series,value,title,color,style){if(num(value)==null)return;series.createPriceLine({price:Number(value),title,color,lineWidth:1,lineStyle:style,axisLabelVisible:true});}
function timeOf(v){if(typeof v==='number')return v>1e12?Math.floor(v/1000):Math.floor(v);const ms=Date.parse(String(v));return Number.isFinite(ms)?Math.floor(ms/1000):String(v).slice(0,10);}
function candles(rows){return (rows||[]).map(x=>({time:timeOf(x[0]),open:+x[1],high:+x[2],low:+x[3],close:+x[4]})).filter(x=>Number.isFinite(x.close)).sort((a,b)=>(a.time>b.time?1:-1)).filter((x,i,a)=>!i||x.time!==a[i-1].time);}
function draw(el,item,r,tf){if(!window.LightweightCharts){el.innerHTML='<div class="chart-empty">차트 모듈을 불러오지 못했어.</div>';return;}const source=r?.charts?.[tf]||item.snapshot.charts?.[tf]||[],data=candles(source);if(!data.length){el.innerHTML='<div class="chart-empty">저장된 차트 데이터 없음</div>';return;}const ch=LightweightCharts.createChart(el,{width:Math.max(1,el.clientWidth),height:270,layout:{background:{type:'solid',color:'#020609'},textColor:'#91a79b'},grid:{vertLines:{color:'#14231c'},horzLines:{color:'#14231c'}},rightPriceScale:{borderVisible:false},timeScale:{rightOffset:5,barSpacing:6,minBarSpacing:2},handleScale:{mouseWheel:true,pinch:true},handleScroll:{pressedMouseMove:true,mouseWheel:true,horzTouchDrag:true}});chartInstances.push(ch);const s=ch.addCandlestickSeries({upColor:'#20dfa4',downColor:'#ff514c',borderUpColor:'#20dfa4',borderDownColor:'#ff514c',wickUpColor:'#20dfa4',wickDownColor:'#ff514c',priceLineVisible:false});s.setData(data);const old=item.snapshot.plan||{},now=r?plan(r):{};line(s,old.average,'당시 평균',COLORS.oldAvg,LightweightCharts.LineStyle.Dashed);line(s,old.stop,'당시 손절',COLORS.oldStop,LightweightCharts.LineStyle.Dashed);line(s,old.t1,'당시 TP1',COLORS.oldT1,LightweightCharts.LineStyle.Dashed);line(s,old.t2,'당시 TP2',COLORS.oldT2,LightweightCharts.LineStyle.Dashed);line(s,now.average,'현재 평균',COLORS.nowAvg,LightweightCharts.LineStyle.Solid);line(s,now.stop,'현재 손절',COLORS.nowStop,LightweightCharts.LineStyle.Solid);line(s,now.t1,'현재 TP1',COLORS.nowT1,LightweightCharts.LineStyle.Solid);line(s,now.t2,'현재 TP2',COLORS.nowT2,LightweightCharts.LineStyle.Solid);ch.timeScale().fitContent();new ResizeObserver(()=>{try{ch.resize(Math.max(1,el.clientWidth),270)}catch(e){}}).observe(el);}
function render(){for(const c of chartInstances){try{c.remove()}catch(e){}}chartInstances=[];const t=store(),items=Object.entries(t).filter(([,x])=>x.tracked||x.bought);const h=host();h.innerHTML=`<div class="tracker-title"><div><h2>⭐ 내 매매 추적 목록</h2><p>${EXCHANGE} 전용 · 별표 순간 계획을 고정하고 현재 분석과 비교해.</p></div><span>${items.length}개 구조</span></div>${items.length?`<div class="tracker-grid">${items.map(([id,x])=>card(id,x)).join('')}</div>`:'<div class="tracker-empty">후보의 ☆를 누르면 당시 계획이 여기에 고정 저장돼.</div>'}`;h.querySelectorAll('[data-buy]').forEach(b=>b.onclick=e=>{e.stopPropagation();const t=store(),x=t[b.dataset.buy];if(!x)return;x.bought=!x.bought;x.events=x.events||[];x.events.push({at:new Date().toISOString(),text:x.bought?'💰 실제 매수함 등록':'실제 매수함 해제'});saveStore(t);render();});h.querySelectorAll('[data-untrack]').forEach(b=>b.onclick=e=>{e.stopPropagation();const t=store(),x=t[b.dataset.untrack];if(!x)return;x.tracked=false;x.events=x.events||[];x.events.push({at:new Date().toISOString(),text:'별표 관심 추적 해제'});saveStore(t);if(!Object.values(t).some(v=>v.market===x.market&&v.tracked))savePins(pins().filter(m=>m!==x.market));render();});requestAnimationFrame(()=>h.querySelectorAll('.trade-track-card').forEach(card=>{const item=store()[card.dataset.trackId],[,,,r]=verdict(item);draw(card.querySelector('[data-chart="day"]'),item,r,'day');draw(card.querySelector('[data-chart="4h"]'),item,r,'4h');}));}
function install(){const original=window.togglePin,pageType=((location.pathname.match(/type_([a-f])\.html/i)||[])[1]||'').toUpperCase();window.togglePin=function(m,b,...args){const was=pins().includes(m),type=b?.dataset?.type||b?.closest('tr')?.dataset?.type||pageType||rowsFor(m)[0]?.type;if(typeof original==='function')original(m,b,...args);else{const p=was?pins().filter(x=>x!==m):[...pins(),m];savePins(p);if(b)b.textContent=was?'☆':'★';}const now=pins().includes(m),t=store();if(now){const r=current(m,type);if(r&&!matchingRecord(t,m,r.type))newRecord(r);}else{let dirty=false;for(const x of Object.values(t)){if(x.market===m&&x.tracked){x.tracked=false;x.events=x.events||[];x.events.push({at:new Date().toISOString(),text:'별표 관심 추적 해제'});dirty=true;}}if(dirty)saveStore(t);}recordChanges();if(location.pathname.endsWith('/watchlist.html')||location.pathname.endsWith('watchlist.html'))render();};}
function css(){const s=document.createElement('style');s.textContent=`.oko-tracker{margin:16px 0 18px;padding:16px;border:1px solid #28513d;border-radius:16px;background:#06100b}.tracker-title,.track-head,.track-verdict{display:flex;justify-content:space-between;gap:12px;align-items:center}.tracker-title h2{margin:0 0 4px}.tracker-title p{margin:0;color:#8fa399;font-size:12px}.tracker-title>span{padding:5px 9px;border:1px solid #315543;border-radius:999px;color:#a7c2b4;font-size:11px}.tracker-grid{display:grid;gap:13px;margin-top:14px}.trade-track-card{padding:14px;border:1px solid #274638;border-left:4px solid #56e6a7;border-radius:14px;background:#08130e}.trade-track-card.yellow{border-left-color:#ffd45f}.trade-track-card.red{border-left-color:#ff667e}.trade-track-card.blue{border-left-color:#58bfff}.track-head b{font-size:16px}.track-head span{display:block;color:#8fa399;font-size:11px}.track-actions{display:flex;gap:7px}.track-actions button{padding:7px 9px;border:1px solid #315543;border-radius:8px;background:#07100c;color:#c7dacf;cursor:pointer}.buy-btn.on{border-color:#ffd45f;color:#ffd45f;background:#2d2508}.track-verdict{margin:10px 0;padding:9px 11px;border-radius:9px;background:#0b1a12}.track-verdict span{color:#9db2a7;font-size:11px}.track-charts,.track-compare{display:grid;grid-template-columns:1fr 1fr;gap:10px}.track-charts>section,.track-compare section{min-width:0;padding:10px;border:1px solid #203c30;border-radius:11px;background:#050a07}.track-chart-title{display:flex;justify-content:space-between;margin-bottom:7px}.track-chart-title span{color:#789489;font-size:10px}.track-chart{width:100%;height:270px;min-width:0}.chart-empty{height:120px;display:grid;place-items:center;color:#789489}.track-compare{margin-top:10px}.track-compare h4{margin:0 0 7px}.track-compare h4 small{float:right;color:#6f8b7d;font-weight:400}.track-compare p{margin:4px 0;color:#a9bcb2;font-size:11px}.track-state{color:#ffd45f!important}.track-reason{color:#789489!important}.track-timeline{margin-top:10px;color:#8fa99b;font-size:11px}.track-timeline summary{cursor:pointer}.track-timeline li{margin:5px 0}.track-timeline li span{display:inline-block;min-width:130px;color:#647d71}.tracker-empty{margin-top:12px;padding:22px;text-align:center;border:1px dashed #29493b;border-radius:11px;color:#789489}.tracker-watch-page #watchRoot,.tracker-watch-page .type-tabs{display:none}@media(max-width:760px){.oko-tracker{padding:11px}.track-head{align-items:flex-start}.track-actions{flex-direction:column}.track-charts,.track-compare{grid-template-columns:1fr}.track-verdict{align-items:flex-start;flex-direction:column}.track-chart{height:250px}}`;document.head.appendChild(s);}
function init(){css();install();ensurePinnedStructures();recordChanges();if(location.pathname.endsWith('watchlist.html'))render();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();'''


def write_tracker_asset(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "trade_tracker.js").write_text(JS, encoding="utf-8")
